## Custom Storage Class for Services

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "${encrypted}"
  kmskeyId: ${kmskeyId}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
