## Set kind to DaemonSet so no affinity is assigned to it

controller:
  kind: DaemonSet
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    externalTrafficPolicy: Cluster
  resources:
    limits:
      cpu: 250m
      memory: 500Mi
    requests:
      cpu: 200m 
      memory: 300Mi

## Enabling metrics for prometheus monitoring

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
